server:
    port: 8081
    compression:
        enabled: true
    servlet:
        session:
            cookie:
                http-only: true
                secure: true
spring:
    datasource:
        url: jdbc:mysql://192.168.74.132:3306/testDB?serverTimezone=UTC
        username: centos
        password: password
        initialization-mode: always
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update     
    jackson:
        time-zone: UTC
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
        
logging:
    level:
        org:
            hibernate:
                SQL: debug
app:
    jwtSecret: JWTSuperSecretKey
    jwtExpirationInMs: 604800000
